#!/bin/bash

##Author: German Matias Traglia, Ph.D
##Address: Departamento de Desarrollo Biotecnologico, Instituto de Higiene
##Description: Read and count each GO term on the functional annotation generated by EggNog Mapper v2 on a single genome.
##Usage: sh count_GO_genomes_2.sh [emapper.annotations file]

argv=$1 ## Input "emapper.annotations file" ###

cat $argv | grep GO: > test_1
cat test_1 | sed -e 's/ /_/g' | awk '{print $13}' > test_2
paste -d, test_2 | sed -e 's/,/\n/g' | sort > test_3
paste -d, -s test_2 | sed -e 's/,/\n/g' | sort | uniq > test_4

lista=$(cat test_4)
for lista in $lista
do
cat test_3 | grep -c "$lista" >> tmp2
done
	paste test_4 tmp2 > count_$argv
	rm -rf test_* tmp2
exit
